### ISSUE TITLE
[develop branch] - Deploying ppyolo, solov2,fcos models will raise MKLDNN error

### ISSUE THREAD

**Issue by OliverLPH** [PaddlePaddle/Paddle#34723]
**System information**
-PaddlePaddle version: https://github.com/PaddlePaddle/Paddle/commit/22c4c189ee5d6e09c3b56f908411b2913ab57c80, https://github.com/PaddlePaddle/Paddle/commit/41c4f7238f7ca6bf35cd6741762831e3e619a087
-CPU: Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
-GPU: None
-OS Platform: Ubuntu1604(image: paddlepaddle/paddle:latest-dev-cuda10.1-cudnn7-gcc82)
-Python version: python 3.7
-Cmake orders
-C++version.txt
-API information
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
cmake commands
```shell
cmake .. -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3.7 -DPYTHON_INCLUDE_DIR:PATH=/usr/local/include/python3.7m -DPYTHON_LIBRARIES:FILEPATH=/usr/local/lib/libpython3.7m.so -DWITH_FLUID_ONLY=ON -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_INFERENCE_API_TEST=OFF -DWITH_MKL=ON -DWITH_MKLDNN=ON -DWITH_AVX=ON -DWITH_TENSORRT=ON -DWITH_PYTHON=ON -DCUDA_ARCH_NAME=All -DWITH_DISTRIBUTE=OFF -DWITH_STRIP=ON
```

**Describe your current behavior**
current error
<img width="819" alt="图片" src="https://user-images.githubusercontent.com/14963836/128683522-e426289d-904a-4415-a02a-0d091a0ec302.png">

**Code to reproduce the issue**
Run test with PaddleDetection codes

```
# clone PaddleDetection
git clone https://github.com/PaddlePaddle/PaddleDetection.git 
cd PaddleDetection
git checkout develop
python -m pip install -r requirments.txt

# download and export ppyolo_r50vd
python tools/export_model.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml --output_dir=inference_model -o weights=https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams

# infer ppyolo_r50vd with mkldnn
python deploy/python/infer.py --model_dir=./inference_model/ppyolo_r50vd_dcn_1x_coco/ --image_file=demo/000000570688.jpg --device=CPU --enable_mkldnn=True
```

you can enable inference log(mkldnn) with comment https://github.com/PaddlePaddle/PaddleDetection/blob/develop/deploy/python/infer.py#L451

**Other info / logs**

```
# download and export solov2
python tools/export_model.py -c configs/solov2/solov2_r50_fpn_1x_coco.yml --output_dir=inference_model -o weights=https://paddledet.bj.bcebos.com/models/solov2_r50_fpn_1x_coco.pdparams
# infer solov2 with mkldnn
python deploy/python/infer.py --model_dir=./inference_model/solov2_r50_fpn_1x_coco/ --image_file=demo/000000570688.jpg --device=CPU --enable_mkldnn=True

# download and export fcos
python tools/export_model.py -c configs/fcos/fcos_r50_fpn_1x_coco.yml --output_dir=inference_model -o weights=https://paddledet.bj.bcebos.com/models/fcos_r50_fpn_1x_coco.pdparams
# infer fcos with mkldnn
python deploy/python/infer.py --mo
python deploy/python/infer.py --model_dir=./inference_model/fcos_r50_fpn_1x_coco/ --image_file=demo/000000570688.jpg --device=CPU --enable_mkldnn=True
```

**Comment by lidanqing-vv** [comment]
use PaddleDetection develop : `0140dbef4bdc6e515a28a1771834f0729dd7163b`

**Comment by lidanqing-vv** [comment]
@jakpiase  Hi, it looks newly integrated FP32/INT8/BF16 kernels cause some models crash. Could you please take a look? Thanks !

**Comment by OliverLPH** [comment]
hi @jakpiase @lidanqing-intel, I add a ppyolo_mbv3 model test in https://github.com/PaddlePaddle/Paddle/pull/34986 and meet a new crash shown below.
```
I0818 06:47:53.379854 31868 device_context.cc:640] oneDNN v2.3.0
I0818 06:47:53.379855 31867 device_context.cc:640] oneDNN v2.3.0
I0818 06:47:53.379859 31870 device_context.cc:640] oneDNN v2.3.0
I0818 06:47:53.380056 31869 device_context.cc:640] oneDNN v2.3.0
W0818 06:47:53.668128 31867 operator.cc:243] expand_v2 raises an exception dnnl::error, could not construct a memory descriptor using a format tag
terminate called after throwing an instance of 'dnnl::error'
  what():  could not construct a memory descriptor using a format tag
Aborted
```
![image](https://user-images.githubusercontent.com/14963836/129866494-a9c90162-f3b0-49a3-9b7e-10b4e813f884.png)

could you please help investigate this error, and enable test in ci [DISABLED_test_ppyolo_mbv3, multi_thread4_mkl_bz2](https://github.com/PaddlePaddle/Paddle/pull/34986/files?file-filters%5B%5D=.cc#diff-9bcdb660ac360f333f570f360388e053d3ecf67da9faf76651c61003088e0986R104)


**reproduce procedure**
if you only want to run on cpu, please disable [gpu test](https://github.com/PaddlePaddle/Paddle/pull/34986/files?file-filters%5B%5D=.cc#diff-9bcdb660ac360f333f570f360388e053d3ecf67da9faf76651c61003088e0986R58).
```
git clone https://github.com/PaddlePaddle/Paddle.git
cd paddle/fluid/inference/tests/infer_ut;
mkdir build && cd build;
cmake .. -DPADDLE_LIB=${PADDLE_LIB} -DDEMO_NAME=test_ppyolo_mbv3 -DWITH_STATIC_LIB=OFF -DWITH_GTEST=ON
make
wget https://paddle-qa.bj.bcebos.com/inference_model/2.1.1/detection/ppyolo_mbv3.tgz;
tar -xvf ppyolo_mbv3.tgz;
./test_ppyolo_mbv3 --modeldir=./test_ppyolo_mbv3
```

**Comment by lidanqing-vv** [comment]
@OliverLPH  PR has been merged, please verify it and then close this issue

Note, there is a compiling issue in PaddleDetection source code, you may need to
```
Add in deploy/cpp/CMakeLists.txt 
+SET(CMAKE_CXX_STANDARD 17)
 SET(PADDLE_DIR "" CACHE PATH "Location of libraries")
 SET(PADDLE_LIB_NAME "" CACHE STRING "libpaddle_inference")
 SET(OPENCV_DIR "" CACHE PATH "Location of libraries")

Add in deploy/cpp/src/main.cc
+#include <experimental/filesystem>
```

**Comment by lidanqing-vv** [comment]
Since @OliverLPH  has approved PR, so I close this issue

**Comment by OliverLPH** [comment]
Hi, @lidanqing-intel 
currently ppyolo_mbv3 model is being fixed, but solov2, fcos models still crash.

**Comment by jakpiase** [comment]
Hi, @OliverLPH 
I have tried to reproduce problems with reshape2 op(solov2, fcos models crash), but without any success. 
Could you please give me more information about environment that you are using to run this model?
Are you using some kind of a virtual machine which doesn't support AVX512 instruction set?
Could you please also send me full logs from running this model with "DNNL_VERBOSE=1" environment variable?

**Comment by OliverLPH** [comment]
Hi, @jakpiase 
my test environment was built by docker, not a virtual machine, and cpu is 6148 which is support AVX512 instruction set. followed are some more environment informations.
```shell
model name	: Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm arat pln pts pku
dokcer images	: registry.baidubce.com/paddlepaddle/paddle:latest-dev-cuda10.1-cudnn7-gcc82

paddle commit	: 31cd1065e718c2d82c3b486e5fd652c6f7d3ff54
paddleDetection	: release/2.2, 259cb5dd32b77bb6da663e0a688901503089eb56
```

The attached files are solov2, fcos models verbose log with "DNNL_VERBOSE=1".
[solov2_log1.txt](https://github.com/PaddlePaddle/Paddle/files/7074289/solov2_log1.txt)
[fcos_log1.txt](https://github.com/PaddlePaddle/Paddle/files/7074290/fcos_log1.txt)

**Comment by jakpiase** [comment]
Hi, I have created a PR which should fix the issue with reshape2 op causing error in fcos model. Solov2 model is causing the same error when I run it with "--enable_mkldnn=True" and "--enable_mkldnn=False". Do you think that it is an issue on our side?
Error in solov2:
![image](https://user-images.githubusercontent.com/62569058/132020946-5c370324-800e-44dc-8a70-de5f13e3f180.png)

**Comment by OliverLPH** [comment]
@jakpiase 
I have confirmed when run with "--enable_mkldnn=False", the issue still exist, so it might not MKLDNN error.
But I can confirmed before https://github.com/PaddlePaddle/Paddle/commit/41c4f7238f7ca6bf35cd6741762831e3e619a087, solov2 can run successes.
@baoachun could you help investigate Solov2 model error when "--enable_mkldnn=False"?

**Comment by baoachun** [comment]
@jakpiase 
Hi，there is another error with using mkldnn to predict solov2，and cpu is ok.
![图片](https://user-images.githubusercontent.com/22114318/133034885-783ca227-5d34-4e90-9a5d-e0887cf03276.png)

**Comment by jakpiase** [comment]
Hi @baoachun, when I run solov2 on paddle/develop branch I am getting that error, no mather if I use oneDNN or not.
![image](https://user-images.githubusercontent.com/62569058/133077145-92bdb13c-65c5-490d-864f-722e4319f626.png)
Could you please give me some steps to reproduce "slice raises an exception"? What commit did you use and what kind of CPU?

**Comment by baoachun** [comment]
> Hi @baoachun, when I run solov2 on paddle/develop branch I am getting that error, no mather if I use oneDNN or not.
> ![image](https://user-images.githubusercontent.com/62569058/133077145-92bdb13c-65c5-490d-864f-722e4319f626.png)
> Could you please give me some steps to reproduce "slice raises an exception"? What commit did you use and what kind of CPU?

Hi, I think you should use PaddleDetection after `00beb736c0091347957be826bb9aef2bd79e04bb` commit with develop branch to produce the slice error.
<img width="624" alt="图片" src="https://user-images.githubusercontent.com/22114318/133079461-8d5db3bb-d5a5-4c0f-8e75-f56161e591b3.png">

**Comment by jakpiase** [comment]
Hi @baoachun #35706 has been merged. Could you please tell me if this issue stil exist?

**Comment by baoachun** [comment]
@jakpiase 
Hi, now the model can reason normally, but the prediction result of solov2 is incorrect.
expect：
![图片](https://user-images.githubusercontent.com/22114318/133600416-2c35760e-2f72-4be4-9b33-6649ffe9302b.png)

wrong：
![图片](https://user-images.githubusercontent.com/22114318/133600476-dabdc50a-b69b-4e44-9ded-94b796d0413c.png)

**Comment by jakpiase** [comment]
Solov2 model should give proper results after #35781 will be merged

**Comment by jakpiase** [comment]
@baoachun #35781 has been merged. Could you please test and confirm if solov2 is giving proper results?

**Comment by baoachun** [comment]
@jakpiase 
OK，I'm working on it, please wait a while.

**Comment by baoachun** [comment]
@jakpiase 
Hi, all problems have been resolved.

**Comment by jakpiase** [comment]
Awesome, thank you for fruitful collaboration
