### ISSUE TITLE
[MKLDNN] MemoryError Problem about `MatmulOneDNNHandler`

### ISSUE THREAD

**Issue by kangguangli** [PaddlePaddle/Paddle#48474]
### Background
I' m cleaning dependencies of old api `fluid.layers.matmul`(https://github.com/PaddlePaddle/Paddle/pull/47988). When i replace all `fluid.layers.matmul` in `python/paddle/fluid/tests/unittests/test_static_save_load.py` with `paddle.matmul`, which will lead the op changes to `matmul_v2` from `matmul`, another test `test_static_save_load_bf16.py` failed while it used the modified part of `test_static_save_load.py`. 

The Error Message is:
```shell
1304: test_static_save_load_bf16 failed
1304:  E
1304: ======================================================================
1304: ERROR: test_ptb_rnn_cpu_bfloat16 (test_static_save_load_bf16.TestSaveLoadBF16)
1304: ----------------------------------------------------------------------
1304: Traceback (most recent call last):
1304:   File "/home/lvyongkang/develop/Paddle/build/python/paddle/fluid/tests/unittests/test_static_save_load_bf16.py", line 116, in test_ptb_rnn_cpu_bfloat16
1304:     fetch_list=fetch_list,
1304:   File "/home/lvyongkang/develop/Paddle/build/python/paddle/fluid/executor.py", line 1586, in run
1304:     return_merged=return_merged,
1304:   File "/home/lvyongkang/develop/Paddle/build/python/paddle/fluid/executor.py", line 1850, in _run_impl
1304:     scope, list(feed.keys()), fetch_list, return_numpy
1304:   File "/home/lvyongkang/develop/Paddle/build/python/paddle/fluid/executor.py", line 672, in run
1304:     scope, feed_names, fetch_list
1304: MemoryError: std::bad_alloc
```

### Problem
I found the error may be related to the following code:
https://github.com/PaddlePaddle/Paddle/blob/9d62efb0e6e5373823039d9eda96cd5905426c0a/paddle/phi/backends/onednn/onednn_reuse.h#L1778-L1792

Once the `x.dims.size() < 3`, the code above will throw memory error and this is the situation i met. 
I found that `python/paddle/fluid/tests/unittests/mkldnn/test_matmul_v2_mkldnn_op.py` covers such test case, but this unit test is disable in CI cause it has some bugs and cannot run correctly.  I think if this unit test `test_matmul_v2_mkldnn_op.py` is fixed, my problem will be solved at the same time.

My Question is:

- does the code above implement as expect? what if `x.dims.size() < 3`? or it's my mistake? 
- will  `test_matmul_v2_mkldnn_op.py`  be fixed and how long will it take?

**Comment by kangguangli** [comment]
@yeliang2258 @jakpiase any progress? Do I need to provide additional information?

**Comment by jakpiase** [comment]
Hi @kangguangli, #48593 should fix this issue

**Comment by kangguangli** [comment]
@jakpiase Thanks for your great work, i tried your PR locally and my problem `test_static_save_load.py` has been fixed. But it seems that `test_matmul_v2_mkldnn_op.py` still has other problems, will it be fixed further?

**Comment by yaomichael** [comment]
@kangguangli can you elaborate what problems you still see, if you no longer care about it, please close it.
@onecatcn

**Comment by kangguangli** [comment]
Personally i'm not working on this now, so i will close this issue.
As for the problem above, I ran the unit test `test_matmul_v2_mkldnn_op` locally with commit  id `7f506669a778f701db993f3aaee9f2b641a893e3` and got following output:
```
  ctest -VV -R test_matmul_v2_mkldnn_op
  UpdateCTestConfiguration  from :/home/lvyongkang/kang/Paddle/build/DartConfiguration.tcl
  UpdateCTestConfiguration  from :/home/lvyongkang/kang/Paddle/build/DartConfiguration.tcl
  Test project /home/lvyongkang/kang/Paddle/build
  Constructing a list of tests
  Done constructing a list of tests
  Updating test list for fixtures
  Added 0 tests to meet fixture requirements
  Checking test dependency graph...
  Checking test dependency graph end
  test 1982
      Start 1982: test_matmul_v2_mkldnn_op
  
  1982: Test command: /home/cmake-3.16.0-Linux-x86_64/bin/cmake "-E" "env" "PYTHONPATH=/home/lvyongkang/kang/Paddle/build/python" "/usr/bin/python3.7" "/home/lvyongkang/kang/Paddle/tools/test_runner.py" "test_matmul_v2_mkldnn_op"
  1982: Test timeout computed to be: 10000000
  1982: I0321 02:41:21.654461 35654 interpretercore.cc:282] New Executor is Running.
  1982: I0321 02:41:21.656883 35654 onednn_context.cc:79] oneDNN v2.7.3
  1982: I0321 02:41:21.799335 35654 interpreter_util.cc:561] Standalone Executor is Used.
  1982: W0321 02:41:24.297547 35654 gpu_resources.cc:85] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.8, Runtime API Version: 11.2
  1982: W0321 02:41:24.301164 35654 gpu_resources.cc:115] device: 0, cuDNN Version: 8.2.
  1982: W0321 02:41:37.853441 35654 interpreter_util.cc:871] matmul_v2 raises an exception dnnl::error, could not construct a memory descriptor using strides
  1982: W0321 02:41:37.863759 35654 interpreter_util.cc:871] matmul_v2 raises an exception dnnl::error, could not create a descriptor for a matmul primitive
  1982: test_matmul_v2_mkldnn_op failed
  1982:  .....ss..ss..ss......ss....ss..ss....ss..ss..ss..ss..ss..ss..ss..ss..ss..ss.EEEEEEEE.E..ss..ss..ss..........
  1982: ======================================================================
  1982: ERROR: test_check_output (test_matmul_v2_mkldnn_op.TestMatMulV2OpReshapeTranspose2DXFloat)
  1982: ----------------------------------------------------------------------
  1982: Traceback (most recent call last):
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/mkldnn/test_matmul_mkldnn_op.py", line 310, in test_check_output
  1982:     self.check_output()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 2083, in check_output
  1982:     check_prim=check_prim,
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1932, in check_output_with_place
  1982:     static_checker.check()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1670, in check
  1982:     self.compare_outputs_with_expects()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1660, in compare_outputs_with_expects
  1982:     self.compare_single_output_with_expect(out_name, expect)
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1638, in compare_single_output_with_expect
  1982:     self._compare_numpy(name, actual_np, expect_np)
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1607, in _compare_numpy
  1982:     equal_nan=equal_nan,
  1982:   File "<__array_function__ internals>", line 6, in allclose
  1982:   File "/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py", line 2256, in allclose
  1982:     res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  1982:   File "<__array_function__ internals>", line 6, in isclose
  1982:   File "/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py", line 2365, in isclose
  1982:     return within_tol(x, y, atol, rtol)
  1982:   File "/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py", line 2346, in within_tol
  1982:     return less_equal(abs(x-y), atol + rtol * abs(y))
  1982: ValueError: operands could not be broadcast together with shapes (2,5,10) (10,10) 
  1982: 
  1982: ======================================================================
  1982: ERROR: test_check_output (test_matmul_v2_mkldnn_op.TestMatMulV2OpReshapeTranspose2DYFloat)
  1982: ----------------------------------------------------------------------
  1982: Traceback (most recent call last):
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/mkldnn/test_matmul_mkldnn_op.py", line 310, in test_check_output
  1982:     self.check_output()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 2083, in check_output
  1982:     check_prim=check_prim,
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1932, in check_output_with_place
  1982:     static_checker.check()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1670, in check
  1982:     self.compare_outputs_with_expects()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1660, in compare_outputs_with_expects
  1982:     self.compare_single_output_with_expect(out_name, expect)
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1638, in compare_single_output_with_expect
  1982:     self._compare_numpy(name, actual_np, expect_np)
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1607, in _compare_numpy
  1982:     equal_nan=equal_nan,
  1982:   File "<__array_function__ internals>", line 6, in allclose
  1982:   File "/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py", line 2256, in allclose
  1982:     res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  1982:   File "<__array_function__ internals>", line 6, in isclose
  1982:   File "/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py", line 2365, in isclose
  1982:     return within_tol(x, y, atol, rtol)
  1982:   File "/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py", line 2346, in within_tol
  1982:     return less_equal(abs(x-y), atol + rtol * abs(y))
  1982: ValueError: operands could not be broadcast together with shapes (2,10,5) (10,10) 
  1982: 
  1982: ======================================================================
  1982: ERROR: test_check_output (test_matmul_v2_mkldnn_op.TestMatMulV2OpReshapeTranspose3DXFloat)
  1982: ----------------------------------------------------------------------
  1982: Traceback (most recent call last):
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/mkldnn/test_matmul_mkldnn_op.py", line 310, in test_check_output
  1982:     self.check_output()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 2083, in check_output
  1982:     check_prim=check_prim,
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1932, in check_output_with_place
  1982:     static_checker.check()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1669, in check
  1982:     self.calculate_output()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1678, in calculate_output
  1982:     place, no_check_set=no_check_set
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1083, in _calc_output
  1982:     return_numpy=False,
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/executor.py", line 1458, in run
  1982:     use_prune=use_prune,
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/executor.py", line 1685, in _run_impl
  1982:     scope, list(feed.keys()), fetch_list, return_numpy
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/executor.py", line 683, in run
  1982:     scope, feed_names, fetch_list
  1982: RuntimeError: could not construct a memory descriptor using strides
  1982: 
  1982: ======================================================================
  1982: ERROR: test_check_output (test_matmul_v2_mkldnn_op.TestMatMulV2OpReshapeTranspose3DYFloat)
  1982: ----------------------------------------------------------------------
  1982: Traceback (most recent call last):
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/mkldnn/test_matmul_mkldnn_op.py", line 310, in test_check_output
  1982:     self.check_output()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 2083, in check_output
  1982:     check_prim=check_prim,
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1932, in check_output_with_place
  1982:     static_checker.check()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1669, in check
  1982:     self.calculate_output()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1678, in calculate_output
  1982:     place, no_check_set=no_check_set
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1083, in _calc_output
  1982:     return_numpy=False,
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/executor.py", line 1458, in run
  1982:     use_prune=use_prune,
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/executor.py", line 1685, in _run_impl
  1982:     scope, list(feed.keys()), fetch_list, return_numpy
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/executor.py", line 683, in run
  1982:     scope, feed_names, fetch_list
  1982: RuntimeError: could not create a descriptor for a matmul primitive
  1982: 
  1982: ======================================================================
  1982: ERROR: test_check_output (test_matmul_v2_mkldnn_op.TestMatMulV2OpReshapeTranspose4DXFloat)
  1982: ----------------------------------------------------------------------
  1982: Traceback (most recent call last):
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/mkldnn/test_matmul_mkldnn_op.py", line 310, in test_check_output
  1982:     self.check_output()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 2083, in check_output
  1982:     check_prim=check_prim,
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1932, in check_output_with_place
  1982:     static_checker.check()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1669, in check
  1982:     self.calculate_output()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1678, in calculate_output
  1982:     place, no_check_set=no_check_set
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1083, in _calc_output
  1982:     return_numpy=False,
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/executor.py", line 1458, in run
  1982:     use_prune=use_prune,
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/executor.py", line 1685, in _run_impl
  1982:     scope, list(feed.keys()), fetch_list, return_numpy
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/executor.py", line 683, in run
  1982:     scope, feed_names, fetch_list
  1982: ValueError: In user code:
  1982: 
  1982:     File "/home/lvyongkang/kang/Paddle/tools/test_runner.py", line 70, in <module>
  1982:       main()
  1982:     File "/home/lvyongkang/kang/Paddle/tools/test_runner.py", line 52, in main
  1982:       res = unittest.TextTestRunner(stream=buffer).run(tests)
  1982:     File "/usr/lib/python3.7/unittest/runner.py", line 176, in run
  1982:       test(result)
  1982:     File "/usr/lib/python3.7/unittest/suite.py", line 84, in __call__
  1982:       return self.run(*args, **kwds)
  1982:     File "/usr/lib/python3.7/unittest/suite.py", line 122, in run
  1982:       test(result)
  1982:     File "/usr/lib/python3.7/unittest/suite.py", line 84, in __call__
  1982:       return self.run(*args, **kwds)
  1982:     File "/usr/lib/python3.7/unittest/suite.py", line 122, in run
  1982:       test(result)
  1982:     File "/usr/lib/python3.7/unittest/case.py", line 676, in __call__
  1982:       return self.run(*args, **kwds)
  1982:     File "/usr/lib/python3.7/unittest/case.py", line 628, in run
  1982:       testMethod()
  1982:     File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/mkldnn/test_matmul_mkldnn_op.py", line 310, in test_check_output
  1982:       self.check_output()
  1982:     File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 2083, in check_output
  1982:       check_prim=check_prim,
  1982:     File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1932, in check_output_with_place
  1982:       static_checker.check()
  1982:     File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1669, in check
  1982:       self.calculate_output()
  1982:     File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1678, in calculate_output
  1982:       place, no_check_set=no_check_set
  1982:     File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1030, in _calc_output
  1982:       op = self._append_ops(block)
  1982:     File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 667, in _append_ops
  1982:       attrs=copy(self.attrs) if hasattr(self, "attrs") else dict(),
  1982:     File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/framework.py", line 4197, in append_op
  1982:       attrs=kwargs.get("attrs", None),
  1982:     File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/framework.py", line 2977, in __init__
  1982:       for frame in traceback.extract_stack():
  1982: 
  1982:     InvalidArgumentError: Tensor dimensions are incorrect for broadcasting.Dimensions in X and Y must be same or equal to 1, but received x_dim[1]=2 and y_dims[1]= 12
  1982:       [Hint: Expected (*x_bd_dims)[i] == (*y_bd_dims)[i] || (*x_bd_dims)[i] == 1 || (*y_bd_dims)[i] == 1 == true, but received (*x_bd_dims)[i] == (*y_bd_dims)[i] || (*x_bd_dims)[i] == 1 || (*y_bd_dims)[i] == 1:0 != true:1.] (at /home/lvyongkang/kang/Paddle/paddle/phi/kernels/onednn/matmul_kernel.cc:90)
  1982:       [operator < matmul_v2 > error]
  1982: 
  1982: ======================================================================
  1982: ERROR: test_check_output (test_matmul_v2_mkldnn_op.TestMatMulV2OpReshapeTranspose4DXYFloat)
  1982: ----------------------------------------------------------------------
  1982: Traceback (most recent call last):
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/mkldnn/test_matmul_mkldnn_op.py", line 310, in test_check_output
  1982:     self.check_output()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 2083, in check_output
  1982:     check_prim=check_prim,
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1932, in check_output_with_place
  1982:     static_checker.check()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1670, in check
  1982:     self.compare_outputs_with_expects()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1660, in compare_outputs_with_expects
  1982:     self.compare_single_output_with_expect(out_name, expect)
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1638, in compare_single_output_with_expect
  1982:     self._compare_numpy(name, actual_np, expect_np)
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1607, in _compare_numpy
  1982:     equal_nan=equal_nan,
  1982:   File "<__array_function__ internals>", line 6, in allclose
  1982:   File "/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py", line 2256, in allclose
  1982:     res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  1982:   File "<__array_function__ internals>", line 6, in isclose
  1982:   File "/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py", line 2365, in isclose
  1982:     return within_tol(x, y, atol, rtol)
  1982:   File "/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py", line 2346, in within_tol
  1982:     return less_equal(abs(x-y), atol + rtol * abs(y))
  1982: ValueError: operands could not be broadcast together with shapes (2,128,128) (2,12,128,128) 
  1982: 
  1982: ======================================================================
  1982: ERROR: test_check_output (test_matmul_v2_mkldnn_op.TestMatMulV2OpReshapeTranspose4DYFloat)
  1982: ----------------------------------------------------------------------
  1982: Traceback (most recent call last):
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/mkldnn/test_matmul_mkldnn_op.py", line 310, in test_check_output
  1982:     self.check_output()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 2083, in check_output
  1982:     check_prim=check_prim,
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1932, in check_output_with_place
  1982:     static_checker.check()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1669, in check
  1982:     self.calculate_output()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1678, in calculate_output
  1982:     place, no_check_set=no_check_set
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1083, in _calc_output
  1982:     return_numpy=False,
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/executor.py", line 1458, in run
  1982:     use_prune=use_prune,
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/executor.py", line 1685, in _run_impl
  1982:     scope, list(feed.keys()), fetch_list, return_numpy
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/executor.py", line 683, in run
  1982:     scope, feed_names, fetch_list
  1982: ValueError: In user code:
  1982: 
  1982:     File "/home/lvyongkang/kang/Paddle/tools/test_runner.py", line 70, in <module>
  1982:       main()
  1982:     File "/home/lvyongkang/kang/Paddle/tools/test_runner.py", line 52, in main
  1982:       res = unittest.TextTestRunner(stream=buffer).run(tests)
  1982:     File "/usr/lib/python3.7/unittest/runner.py", line 176, in run
  1982:       test(result)
  1982:     File "/usr/lib/python3.7/unittest/suite.py", line 84, in __call__
  1982:       return self.run(*args, **kwds)
  1982:     File "/usr/lib/python3.7/unittest/suite.py", line 122, in run
  1982:       test(result)
  1982:     File "/usr/lib/python3.7/unittest/suite.py", line 84, in __call__
  1982:       return self.run(*args, **kwds)
  1982:     File "/usr/lib/python3.7/unittest/suite.py", line 122, in run
  1982:       test(result)
  1982:     File "/usr/lib/python3.7/unittest/case.py", line 676, in __call__
  1982:       return self.run(*args, **kwds)
  1982:     File "/usr/lib/python3.7/unittest/case.py", line 628, in run
  1982:       testMethod()
  1982:     File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/mkldnn/test_matmul_mkldnn_op.py", line 310, in test_check_output
  1982:       self.check_output()
  1982:     File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 2083, in check_output
  1982:       check_prim=check_prim,
  1982:     File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1932, in check_output_with_place
  1982:       static_checker.check()
  1982:     File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1669, in check
  1982:       self.calculate_output()
  1982:     File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1678, in calculate_output
  1982:       place, no_check_set=no_check_set
  1982:     File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1030, in _calc_output
  1982:       op = self._append_ops(block)
  1982:     File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 667, in _append_ops
  1982:       attrs=copy(self.attrs) if hasattr(self, "attrs") else dict(),
  1982:     File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/framework.py", line 4197, in append_op
  1982:       attrs=kwargs.get("attrs", None),
  1982:     File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/framework.py", line 2977, in __init__
  1982:       for frame in traceback.extract_stack():
  1982: 
  1982:     InvalidArgumentError: Tensor dimensions are incorrect for broadcasting.Dimensions in X and Y must be same or equal to 1, but received x_dim[1]=12 and y_dims[1]= 2
  1982:       [Hint: Expected (*x_bd_dims)[i] == (*y_bd_dims)[i] || (*x_bd_dims)[i] == 1 || (*y_bd_dims)[i] == 1 == true, but received (*x_bd_dims)[i] == (*y_bd_dims)[i] || (*x_bd_dims)[i] == 1 || (*y_bd_dims)[i] == 1:0 != true:1.] (at /home/lvyongkang/kang/Paddle/paddle/phi/kernels/onednn/matmul_kernel.cc:90)
  1982:       [operator < matmul_v2 > error]
  1982: 
  1982: ======================================================================
  1982: ERROR: test_check_output (test_matmul_v2_mkldnn_op.TestMatMulV2OpTransposeReshapeBasicFloat)
  1982: ----------------------------------------------------------------------
  1982: Traceback (most recent call last):
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/mkldnn/test_matmul_mkldnn_op.py", line 508, in test_check_output
  1982:     self.check_output()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 2083, in check_output
  1982:     check_prim=check_prim,
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1932, in check_output_with_place
  1982:     static_checker.check()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1670, in check
  1982:     self.compare_outputs_with_expects()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1660, in compare_outputs_with_expects
  1982:     self.compare_single_output_with_expect(out_name, expect)
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1638, in compare_single_output_with_expect
  1982:     self._compare_numpy(name, actual_np, expect_np)
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1607, in _compare_numpy
  1982:     equal_nan=equal_nan,
  1982:   File "<__array_function__ internals>", line 6, in allclose
  1982:   File "/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py", line 2256, in allclose
  1982:     res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  1982:   File "<__array_function__ internals>", line 6, in isclose
  1982:   File "/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py", line 2365, in isclose
  1982:     return within_tol(x, y, atol, rtol)
  1982:   File "/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py", line 2346, in within_tol
  1982:     return less_equal(abs(x-y), atol + rtol * abs(y))
  1982: ValueError: operands could not be broadcast together with shapes (8,12,128,64) (8,128,768) 
  1982: 
  1982: ======================================================================
  1982: ERROR: test_check_output (test_matmul_v2_mkldnn_op.TestMatMulV2OpTransposeReshapeOtherDimFloat)
  1982: ----------------------------------------------------------------------
  1982: Traceback (most recent call last):
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/mkldnn/test_matmul_mkldnn_op.py", line 508, in test_check_output
  1982:     self.check_output()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 2083, in check_output
  1982:     check_prim=check_prim,
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1932, in check_output_with_place
  1982:     static_checker.check()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1670, in check
  1982:     self.compare_outputs_with_expects()
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1660, in compare_outputs_with_expects
  1982:     self.compare_single_output_with_expect(out_name, expect)
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1638, in compare_single_output_with_expect
  1982:     self._compare_numpy(name, actual_np, expect_np)
  1982:   File "/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1607, in _compare_numpy
  1982:     equal_nan=equal_nan,
  1982:   File "<__array_function__ internals>", line 6, in allclose
  1982:   File "/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py", line 2256, in allclose
  1982:     res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  1982:   File "<__array_function__ internals>", line 6, in isclose
  1982:   File "/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py", line 2365, in isclose
  1982:     return within_tol(x, y, atol, rtol)
  1982:   File "/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py", line 2346, in within_tol
  1982:     return less_equal(abs(x-y), atol + rtol * abs(y))
  1982: ValueError: operands could not be broadcast together with shapes (11,12,14,13) (11,14,156) 
  1982: 
  1982: ----------------------------------------------------------------------
  1982: Ran 108 tests in 18.029s
  1982: 
  1982: FAILED (errors=9, skipped=38)
  1982: 
  1982: ['/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests', '/home/lvyongkang/kang/Paddle/tools', '/home/lvyongkang/kang/Paddle/build/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/local/lib/python3.7/dist-packages/paddleslim-0.0.0.dev0-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/paddlecloudplatform-3.1.2-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/custom_setup_op_relu_model_static_multidevices-0.0.0-py3.7-linux-x86_64.egg', '/usr/local/lib/python3.7/dist-packages/rich-13.3.2-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/typer-0.7.0-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/uvicorn-0.21.1-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/fastapi-0.95.0-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/paddle2onnx-1.0.6-py3.7-linux-x86_64.egg', '/usr/local/lib/python3.7/dist-packages/huggingface_hub-0.13.2-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/sentencepiece-0.1.97-py3.7-linux-x86_64.egg', '/usr/local/lib/python3.7/dist-packages/paddlefsl-1.1.0-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/datasets-2.10.1-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/multiprocess-0.70.12.2-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/dill-0.3.4-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/seqeval-1.2.2-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/colorama-0.4.6-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/colorlog-6.7.0-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/jieba-0.42.1-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/Pygments-2.14.0-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/markdown_it_py-2.2.0-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/h11-0.14.0-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/starlette-0.26.1-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/pydantic-1.10.6-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/xxhash-3.2.0-py3.7-linux-x86_64.egg', '/usr/local/lib/python3.7/dist-packages/responses-0.18.0-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/pyarrow-11.0.0-py3.7-linux-x86_64.egg', '/usr/local/lib/python3.7/dist-packages/mdurl-0.1.2-py3.7.egg', '/usr/local/lib/python3.7/dist-packages/paddlenlp-2.5.2.post0-py3.7.egg', '/usr/lib/python3/dist-packages', '/home/lvyongkang/kang/Paddle/tools', '/home/lvyongkang/kang/Paddle/build/python/paddle/fluid/tests/unittests/mkldnn']
  1/1 Test #1982: test_matmul_v2_mkldnn_op .........***Failed   22.26 sec
  
  0% tests passed, 1 tests failed out of 1
  
  Total Test time (real) =  22.36 sec
  
  The following tests FAILED:
          1982 - test_matmul_v2_mkldnn_op (Failed)
  Errors while running CTest
```

I'm not sure what's the problem here and whether it implies that the onednn kernel of matmul has bug. I think this should be fixed if this test is used to verify the correctness of onednn kernel. Thanks for your work.

**Comment by jakpiase** [comment]
Hi, it appears that @Silv3S changes did fix that issue. Now `test_matmul_v2_mkldnn_op` works on current paddle develop branch

**Comment by kangguangli** [comment]
Thanks for your work. @XieYunshen can you enable this test in CI again?
